apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: style-transfer
  namespace: adroit-lock-289808
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/adroit-lock-289808/style-transfer-app
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
  traffic:
    - percent: 100
      latestRevision: true